CREATE TABLE `events` (
   `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
   `name` VARCHAR(255) NOT NULL,
   `short_name` VARCHAR(25) NOT NULL,
   `qr_code` BOOLEAN NOT NULL,
   `description` VARCHAR(2047) NOT NULL,
   `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
   `updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   `start_time` DATETIME NOT NULL,
   `end_time` DATETIME NOT NULL,
   `tag` ENUM('HACKATHON', 'SCHEDULE') NOT NULL,
   PRIMARY KEY (`id`))
